name: Maven Build and Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
  
    - name: Build with Maven
      run: mvn -B install --file pom.xml -P production
    
    - name: Publish to GitHub Packages Apache Maven
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
       echo "<settings><servers><server><id>github</id><username>luthesebas</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > $GITHUB_WORKSPACE/settings.xml
       mvn deploy -s $GITHUB_WORKSPACE/settings.xml
